/proc_fault/navigation/dvl/timestamp_ms: 1000
/proc_fault/navigation/dvl/enable: false

/proc_fault/navigation/depth/timestamp_ms: 1000
/proc_fault/navigation/depth/enable: false

/proc_fault/navigation/imu/timestamp_ms: 1000
/proc_fault/navigation/imu/enable: false

/proc_fault/navigation/control/timestamp_ms: 1000
/proc_fault/navigation/control/enable: false

/proc_fault/vision/camera/timestamp_ms: 1000
/proc_fault/vision/camera/enable: false

/proc_fault/vision/proc_image_processing/enable: false

/proc_fault/vision/proc_detection/enable: false

/proc_fault/mapping/sonar/timestamp_ms: 1000
/proc_fault/mapping/sonar/enable: false

/proc_fault/mapping/procMapping/timestamp_ms: 1000
/proc_fault/mapping/procMapping/enable: false

/proc_fault/hydro/providerHydro/timestamp_ms: 1000
/proc_fault/hydro/providerHydro/enable: false

/proc_fault/hydro/procHydro/timestamp_ms: 1000
/proc_fault/hydro/procHydro/enable: false

/proc_fault/power/providerPower/timestamp_ms: 1000
/proc_fault/power/providerPower/enable: false

/proc_fault/power/providerThruster/enable: false

/proc_fault/internal_com/rs485/timestamp_ms: 1000
/proc_fault/internal_com/rs485/enable: false

/proc_fault/io/providerActuator/enable: false

/proc_fault/io/procActuator/enable: false

/proc_fault/under_water_com/providerCom/enable: false

/proc_fault/initial_node_sleep_second: 30
/proc_fault/loop_sleep_time_second: 1